services:
  # Watchtower polls for updates and downloads them as they come out.
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      WATCHTOWER_POLL_INTERVAL: 30
      WATCHTOWER_LABEL_ENABLE: true

  # nginx:
  #   image: nginx
  #   ports:
  #     - 443:443
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #     - /etc/letsencrypt/:/etc/letsencrypt/:ro

  oga-website:
    image: ghcr.io/oxford-guild-of-assassins/oga-website
    labels:
      com.centurylinklabs.watchtower.enable: "true"